// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxRateCollector.Infrastructure.Data;

#nullable disable

namespace TaxRateCollector.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260415000001_AddHierarchyAndSourceDocument")]
    partial class AddHierarchyAndSourceDocument
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("TaxRateCollector.Core.Entities.ChangeLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Acknowledged")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("JurisdictionId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("NewRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OldRate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JurisdictionId");

                    b.ToTable("ChangeLog", (string)null);
                });

            modelBuilder.Entity("TaxRateCollector.Core.Entities.Jurisdiction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FipsCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JurisdictionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JurisdictionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FipsCode")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("Jurisdictions");
                });

            modelBuilder.Entity("TaxRateCollector.Core.Entities.ScrapeRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChangesDetected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StartedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalScraped")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ScrapeRuns");
                });

            modelBuilder.Entity("TaxRateCollector.Core.Entities.SourceDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FetchedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RawContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TaxRateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TaxRateId")
                        .IsUnique();

                    b.ToTable("SourceDocuments");
                });

            modelBuilder.Entity("TaxRateCollector.Core.Entities.TaxRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EffectiveDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JurisdictionId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Rate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RateType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RawValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ScrapeRunId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScrapedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JurisdictionId");

                    b.HasIndex("ScrapeRunId");

                    b.ToTable("TaxRates");
                });

            modelBuilder.Entity("TaxRateCollector.Core.Entities.ChangeLogEntry", b =>
                {
                    b.HasOne("TaxRateCollector.Core.Entities.Jurisdiction", "Jurisdiction")
                        .WithMany("ChangeLogEntries")
                        .HasForeignKey("JurisdictionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jurisdiction");
                });

            modelBuilder.Entity("TaxRateCollector.Core.Entities.Jurisdiction", b =>
                {
                    b.HasOne("TaxRateCollector.Core.Entities.Jurisdiction", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("TaxRateCollector.Core.Entities.SourceDocument", b =>
                {
                    b.HasOne("TaxRateCollector.Core.Entities.TaxRate", "TaxRate")
                        .WithOne("SourceDocument")
                        .HasForeignKey("TaxRateCollector.Core.Entities.SourceDocument", "TaxRateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaxRate");
                });

            modelBuilder.Entity("TaxRateCollector.Core.Entities.TaxRate", b =>
                {
                    b.HasOne("TaxRateCollector.Core.Entities.Jurisdiction", "Jurisdiction")
                        .WithMany("TaxRates")
                        .HasForeignKey("JurisdictionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaxRateCollector.Core.Entities.ScrapeRun", "ScrapeRun")
                        .WithMany("TaxRates")
                        .HasForeignKey("ScrapeRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jurisdiction");

                    b.Navigation("ScrapeRun");
                });

            modelBuilder.Entity("TaxRateCollector.Core.Entities.Jurisdiction", b =>
                {
                    b.Navigation("ChangeLogEntries");

                    b.Navigation("Children");

                    b.Navigation("TaxRates");
                });

            modelBuilder.Entity("TaxRateCollector.Core.Entities.ScrapeRun", b =>
                {
                    b.Navigation("TaxRates");
                });

            modelBuilder.Entity("TaxRateCollector.Core.Entities.TaxRate", b =>
                {
                    b.Navigation("SourceDocument");
                });
#pragma warning restore 612, 618
        }
    }
}
